FROM alpine

RUN apk add --no-cache unzip openjdk11-jre bash zip yq

ENV SONAR_SCANNER_VERSION=4.3.0.2102
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk/jre
ENV PATH $PATH:/sonar-scanner/bin:/usr/lib/jvm/java-11-openjdk/jre/bin:/usr/lib/jvm/java-11-openjdk/bin

COPY ./main.sh /main.sh

# Trivy
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3


ADD "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip" /

RUN  unzip sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip \
      && ln -s /sonar-scanner-${SONAR_SCANNER_VERSION} /sonar-scanner \
      && rm -f sonar-scanner-cli-*.zip

ENTRYPOINT ["/bin/bash", "/main.sh"]